version: '2.1'
services:
    zookeeper:
      image: confluent/zookeeper
      ports:
        - "2181:2181"

    kafka:
      image: wurstmeister/kafka:0.9.0.0-1
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 10.0.75.1
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    kafka-manager:
      image: sheepkiller/kafka-manager:latest
      ports:
        - "9000:9000"
      links:
        - zookeeper
        - kafka
      environment:
        ZK_HOSTS: zookeeper:2181
        APPLICATION_SECRET: letmein
        KM_ARGS: -Djava.net.preferIPv4Stack=true
