version: '3.7'

services:
  zookeeper:
    image: confluent/zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
    - zookeeper
  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    ports:
    - "9000:9000"
    links:
    - zookeeper
    - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:5.3.0
    hostname: kafka-schema-registry
    ports:
    - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 192.168.99.100:9092
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
    - zookeeper
    - kafka

  schema-registry-ui:
    image: landoop/schema-registry-ui:0.9.4
    hostname: kafka-schema-registry-ui
    ports:
    - "8001:8000"
    environment:
      SCHEMAREGISTRY_URL: http://192.168.99.100:8081/
      PROXY: "true"
    depends_on:
    - kafka-schema-registry
